### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by keatit71** [DeathsGun/ModManager#66] opened 2021-10-01 16:25 UTC
**Describe the bug**
Downloads new versions of mods with updated but it doesn't delete old version and in the case of Detail armor bar it downloaded the new version of the mod for the wrong version of minecraft

**To Reproduce**
1. Have old versions of mods
2. Open game and update in-game
3. Try to relaunch and get warned about duplicate mods

**Expected behavior**
Update mods to correct version and delete old version of mods

**Screenshots**
![image](https://user-images.githubusercontent.com/42551576/135652275-162c8ad6-cef0-4820-ae77-fba9cab56c1c.png)

** Please complete the following information:**
 - OS: Windows 10
 - Minecraft version 1.17.1
 - Version v1.1.0-alpha+1.17

**Comment by DeathsGun** [comment] 2021-10-01 16:28
Duplicate of #51 i will open it again for discussion and progress tracking

**Closed** 2021-10-01 16:28 UTC
Labels: bug, duplicate
