### ISSUE TITLE
Error updating mods on fabric 1.17.1

### ISSUE THREAD

**Issue by Zano1999** [DeathsGun/ModManager#42] opened 2021-08-25 16:36 UTC
When i try to update a mod i get the following error message:

https://imgur.com/4DwnqAo

**Comment by DeathsGun** [comment] 2021-08-28 11:01
This will be fixed with the kotlin rewrite

**Comment by DeathsGun** [comment] 2021-09-15 10:23
Should be fixed

**Closed by DeathsGun** 2021-09-15 10:23 UTC
Labels: bug

**Comment by Zano1999** [comment] 2021-09-15 10:29
Unfortunately no, i had already tried the latest version whe you uploaded it

**Comment by DeathsGun** [comment] 2021-09-15 10:31
The latest version isn't released yet on modrinth you can only build it yourself

**Comment by Zano1999** [comment] 2021-09-15 10:34
What do you mean I have to build it?

**Comment by DeathsGun** [comment] 2021-09-15 10:36
I haven't released it on modrinth because it's missing some translations.
So it's only on github but i can upload a preview for you here if want.

**Comment by DeathsGun** [comment] 2021-09-15 10:51
Here is a preview: 
[modmanager-1.1.0+1.17-alpha.jar.zip](https://github.com/DeathsGun/ModManager/files/7169435/modmanager-1.1.0%2B1.17-alpha.jar.zip)

**Comment by Zano1999** [comment] 2021-09-15 16:05
Ok, with this versione the problem is solved but the old version of an updated mod stay in the mod folder, is it normal?

**Comment by DeathsGun** [comment] 2021-09-15 16:06
With windows?

**Comment by Zano1999** [comment] 2021-09-15 16:07
yes

**Comment by DeathsGun** [comment] 2021-09-15 16:08
Yeah that's a problem how Windows deletes files it does not allow programs to delete files while their open

**Comment by Zano1999** [comment] 2021-09-15 16:16
What a shame, it would have been very convenient, anyway, thanks for the quick replies :)

**Comment by DeathsGun** [comment] 2021-09-15 16:18
It works on linux and mac os but i'm searching for a way on windows

**Comment by Felix14-v2** [comment] 2021-09-18 15:06
Maybe it will be possible to start deleting updated mods before they are loaded at the next launch?

**Comment by DeathsGun** [comment] 2021-09-18 15:09
Unfortunately fabric has no entry point for mods to get called before all other mods are loaded.

Also discussion for this should be continued in #51 as it's about this exact problem.

**Comment by Felix14-v2** [comment] 2021-09-18 15:33
I thought if ThatOrThis can run before other mods, then there is [some way](https://github.com/Devan-Kerman/GrossFabricHacks/wiki/Super-Early-Init).

**Comment by DeathsGun** [comment] 2021-09-18 15:37
The problem is that when fabric opens the jar it will get locked by windows so even if we use a super early entry point to delete the mods which are marked to be removed, then fabric will already has looked into the jar files and windows will have created a file lock which prevents us from deleting it.

I think it's better to run a small program after Minecraft stops and it will wait until the file lock is removed and delete it

**Comment by Zano1999** [comment] 2021-09-18 15:46
It is possible to blacklist a mod?

Because some mods are more updated only on curseforge, but your mod tell me to update they to the latest version of modrinth (an older one)

**Comment by DeathsGun** [comment] 2021-09-18 15:50
So you have a newer version from curseforge installed and on modrinth it's older and my mod marks it as outdated? If that's the case then it's a bug

**Comment by Zano1999** [comment] 2021-09-18 16:00
Yes, here an example

![immagine_2021-09-18_180052](https://user-images.githubusercontent.com/42555362/133894962-959d95ad-479d-487c-9408-67d6ab832619.png)
